# Set the build language to Python
language: python

# Set the python version to 3.5
python:
  - "3.6"

# Install the codecov pip dependency
install:
  - pip install pandas
  #- pip install codecov
  #- pip install coverage

# Run the unit test
script:
  - pytest

# Push the results back to codecov
after_success:
  #- codecov
